apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: robotsentience-com-tls
spec:
  secretName: robotsentience-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: robotsentience.com
  dnsNames:
    - robotsentience.com
    - www.robotsentience.com
